version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=mbdb
      - POSTGRES_DB=mbdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
        - "5432:5432"
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
    volumes:
      - azdata:/data
  redis:
    image: "redis:alpine"
  web:
    build: .
    command:
    - bash
    - '-c'
    - |
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=postgres://mbdb@db/mbdb
      - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
      - SALESFORCE_CONSUMER_KEY
      - SALESFORCE_CONSUMER_SECRET
      - SALESFORCE_USER
      - SALESFORCE_PASSWORD
      - SALESFORCE_HOST
      - DEFAULT_WORKING_DIRECTORY
      - AZURE_EMULATED_MODE=true
      - AZURE_ACCOUNT_NAME=devstoreaccount1
      - AZURE_ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - AZURE_CONTAINER=media
      - AZURE_CUSTOM_DOMAIN=azurite:10000
      - MEDIA_URL=http://localhost:10000/media/
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - azurite
  celerybeat:
    build: .
    command:
    - bash
    - '-c'
    - |
      pip install -r requirements.txt &&
      celery -A missionbit worker -B -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - DATABASE_URL=postgres://mbdb@db/mbdb
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

volumes:
  pgdata:
  azdata:
