RACE_CHOICES = (
    ("American Indian/Alaskan Native", "American Indian/Alaskan Native"),
    ("Asian", "Asian"),
    ("Black/African American", "Black/African American"),
    (
        "Native Hawaiian/Other Pacific Islander",
        "Native Hawaiian/Other Pacific Islander",
    ),
    ("White", "White"),
    (
        "American Indian/Alaskan Native AND Black/African American",
        "American Indian/Alaskan Native AND Black/African American",
    ),
    (
        "American Indian/Alaskan Native AND White",
        "American Indian/Alaskan Native AND White",
    ),
    ("Asian AND White", "Asian AND White"),
    ("Black/African American AND White", "Black/African American AND White"),
    ("Other/Multiracial", "Other/Multiracial"),
    ("Politely Decline", "Politely Decline"),
)

ETHNICITY_CHOICES = (
    ("Hispanic/Latinx", "Hispanic/Latinx"),
    ("Not Hispanic/Latinx", "Not Hispanic/Latinx"),
    ("Politely Decline", "Politely Decline"),
)

GENDER_CHOICES = (
    ("Female", "Female"),
    ("Male", "Male"),
    ("Genderqueer/Gender Non-binary", "Genderqueer/Gender Non-binary"),
    ("Trans Female", "Trans Female"),
    ("Trans Male", "Trans Male"),
    ("Other", "Not Listed"),
)

GRAD_YEAR_CHOICES = (
    ("2019", "2019"),
    ("2020", "2020"),
    ("2021", "2021"),
    ("2022", "2022"),
    ("2023", "2023"),
    ("2024", "2024"),
    ("2025", "2025"),
    ("2026", "2026"),
    ("2027", "2027"),
    ("2028", "2028"),
    ("2029", "2029"),
    ("2030", "2030"),
    ("2031", "2031"),
    ("2032", "2032"),
    ("2033", "2033"),
    ("2034", "2034"),
)

COURSE_CHOICES = (
    ("Android Game Design", "Android Game Design"),
    ("Intro to Web Programming", "Intro to Web Programming"),
    ("Field Trips", "Field Trips"),
    ("Intro to Game Design with Unity", "Intro to Game Design with Unity"),
    ("Web Design 101", "Web Design 101"),
    ("Mobile App Dev with Ionic", "Mobile App Dev with Ionic"),
    ("MB Internship", "MB Internship"),
    ("Structured Study Program", "Structured Study Program"),
)

MEETING_DAYS_CHOICES = (("M/W", "M/W"), ("T/R", "T/R"), ("M-F", "M-F"))

ACCOUNT_TYPE_CHOICES = (
    ("School", "School"),
    ("Foundation", "Foundation"),
    ("Government", "Government"),
    ("Business", "Business"),
    ("Nonprofit", "Nonprofit"),
)

SALUTATION_CHOICES = (
    ("Mr.", "Mr."),
    ("Ms.", "Ms."),
    ("Mrs.", "Mrs."),
    ("Dr.", "Dr."),
    ("Prof.", "Prof."),
)

STATE_CHOICES = (
    ("AC", "Acre"),
    ("AG", "Agrigento"),
    ("AG", "Aguascalientes"),
    ("AL", "Alabama"),
    ("AL", "Alagoas"),
    ("AK", "Alaska"),
    ("AB", "Alberta"),
    ("AL", "Alessandria"),
    ("AP", "Amapá"),
    ("AM", "Amazonas"),
    ("AN", "Ancona"),
    ("AN", "Andaman and Nicobar Islands"),
    ("AP", "Andhra Pradesh"),
    ("34", "Anhui"),
    ("AO", "Aosta"),
    ("AR", "Arezzo"),
    ("AZ", "Arizona"),
    ("AR", "Arkansas"),
    ("AR", "Arunachal Pradesh"),
    ("AP", "Ascoli Piceno"),
    ("AS", "Assam"),
    ("AT", "Asti"),
    ("ACT", "Australian Capital Territory"),
    ("AV", "Avellino"),
    ("BA", "Bahia"),
    ("BC", "Baja California"),
    ("BS", "Baja California Sur"),
    ("BA", "Bari"),
    ("BT", "Barletta-Andria-Trani"),
    ("11", "Beijing"),
    ("BL", "Belluno"),
    ("BN", "Benevento"),
    ("BG", "Bergamo"),
    ("BI", "Biella"),
    ("BR", "Bihar"),
    ("BO", "Bologna"),
    ("BZ", "Bolzano"),
    ("BS", "Brescia"),
    ("BR", "Brindisi"),
    ("BC", "British Columbia"),
    ("CA", "Cagliari"),
    ("CA", "California"),
    ("CL", "Caltanissetta"),
    ("CM", "Campeche"),
    ("CB", "Campobasso"),
    ("CI", "Carbonia-Iglesias"),
    ("CW", "Carlow"),
    ("CE", "Caserta"),
    ("CT", "Catania"),
    ("CZ", "Catanzaro"),
    ("CN", "Cavan"),
    ("CE", "Ceará"),
    ("CH", "Chandigarh"),
    ("CT", "Chhattisgarh"),
    ("CS", "Chiapas"),
    ("CH", "Chieti"),
    ("CH", "Chihuahua"),
    ("71", "Chinese Taipei"),
    ("50", "Chongqing"),
    ("CE", "Clare"),
    ("CO", "Coahuila"),
    ("CL", "Colima"),
    ("CO", "Colorado"),
    ("CO", "Como"),
    ("CT", "Connecticut"),
    ("CO", "Cork"),
    ("CS", "Cosenza"),
    ("CR", "Cremona"),
    ("KR", "Crotone"),
    ("CN", "Cuneo"),
    ("DN", "Dadra and Nagar Haveli"),
    ("DD", "Daman and Diu"),
    ("DE", "Delaware"),
    ("DL", "Delhi"),
    ("DC", "District of Columbia"),
    ("DF", "Distrito Federal"),
    ("DL", "Donegal"),
    ("D", "Dublin"),
    ("DG", "Durango"),
    ("EN", "Enna"),
    ("ES", "Espírito Santo"),
    ("DF", "Federal District"),
    ("FM", "Fermo"),
    ("FE", "Ferrara"),
    ("FI", "Florence"),
    ("FL", "Florida"),
    ("FG", "Foggia"),
    ("FC", "Forlì-Cesena"),
    ("FR", "Frosinone"),
    ("35", "Fujian"),
    ("G", "Galway"),
    ("62", "Gansu"),
    ("GE", "Genoa"),
    ("GA", "Georgia"),
    ("GA", "Goa"),
    ("GO", "Goiás"),
    ("GO", "Gorizia"),
    ("GR", "Grosseto"),
    ("GT", "Guanajuato"),
    ("44", "Guangdong"),
    ("45", "Guangxi"),
    ("GR", "Guerrero"),
    ("52", "Guizhou"),
    ("GJ", "Gujarat"),
    ("46", "Hainan"),
    ("HR", "Haryana"),
    ("HI", "Hawaii"),
    ("13", "Hebei"),
    ("23", "Heilongjiang"),
    ("41", "Henan"),
    ("HG", "Hidalgo"),
    ("HP", "Himachal Pradesh"),
    ("91", "Hong Kong"),
    ("42", "Hubei"),
    ("43", "Hunan"),
    ("ID", "Idaho"),
    ("IL", "Illinois"),
    ("IM", "Imperia"),
    ("IN", "Indiana"),
    ("IA", "Iowa"),
    ("IS", "Isernia"),
    ("JA", "Jalisco"),
    ("JK", "Jammu and Kashmir"),
    ("JH", "Jharkhand"),
    ("32", "Jiangsu"),
    ("36", "Jiangxi"),
    ("22", "Jilin"),
    ("KS", "Kansas"),
    ("KA", "Karnataka"),
    ("KY", "Kentucky"),
    ("KL", "Kerala"),
    ("KY", "Kerry"),
    ("KE", "Kildare"),
    ("KK", "Kilkenny"),
    ("AQ", "L'Aquila"),
    ("LD", "Lakshadweep"),
    ("LS", "Laois"),
    ("SP", "La Spezia"),
    ("LT", "Latina"),
    ("LE", "Lecce"),
    ("LC", "Lecco"),
    ("LM", "Leitrim"),
    ("21", "Liaoning"),
    ("LK", "Limerick"),
    ("LI", "Livorno"),
    ("LO", "Lodi"),
    ("LD", "Longford"),
    ("LA", "Louisiana"),
    ("LH", "Louth"),
    ("LU", "Lucca"),
    ("92", "Macao"),
    ("MC", "Macerata"),
    ("MP", "Madhya Pradesh"),
    ("MH", "Maharashtra"),
    ("ME", "Maine"),
    ("MN", "Manipur"),
    ("MB", "Manitoba"),
    ("MN", "Mantua"),
    ("MA", "Maranhão"),
    ("MD", "Maryland"),
    ("MS", "Massa and Carrara"),
    ("MA", "Massachusetts"),
    ("MT", "Matera"),
    ("MT", "Mato Grosso"),
    ("MS", "Mato Grosso do Sul"),
    ("MO", "Mayo"),
    ("MH", "Meath"),
    ("VS", "Medio Campidano"),
    ("ML", "Meghalaya"),
    ("ME", "Messina"),
    ("ME", "Mexico State"),
    ("MI", "Michigan"),
    ("MI", "Michoacán"),
    ("MI", "Milan"),
    ("MG", "Minas Gerais"),
    ("MN", "Minnesota"),
    ("MS", "Mississippi"),
    ("MO", "Missouri"),
    ("MZ", "Mizoram"),
    ("MO", "Modena"),
    ("MN", "Monaghan"),
    ("MT", "Montana"),
    ("MB", "Monza and Brianza"),
    ("MO", "Morelos"),
    ("NL", "Nagaland"),
    ("NA", "Naples"),
    ("NA", "Nayarit"),
    ("NE", "Nebraska"),
    ("15", "Nei Mongol"),
    ("NV", "Nevada"),
    ("NB", "New Brunswick"),
    ("NL", "Newfoundland and Labrador"),
    ("NH", "New Hampshire"),
    ("NJ", "New Jersey"),
    ("NM", "New Mexico"),
    ("NSW", "New South Wales"),
    ("NY", "New York"),
    ("64", "Ningxia"),
    ("NC", "North Carolina"),
    ("ND", "North Dakota"),
    ("NT", "Northern Territory"),
    ("NT", "Northwest Territories"),
    ("NO", "Novara"),
    ("NS", "Nova Scotia"),
    ("NL", "Nuevo León"),
    ("NU", "Nunavut"),
    ("NU", "Nuoro"),
    ("OA", "Oaxaca"),
    ("OR", "Odisha"),
    ("OY", "Offaly"),
    ("OG", "Ogliastra"),
    ("OH", "Ohio"),
    ("OK", "Oklahoma"),
    ("OT", "Olbia-Tempio"),
    ("ON", "Ontario"),
    ("OR", "Oregon"),
    ("OR", "Oristano"),
    ("PD", "Padua"),
    ("PA", "Palermo"),
    ("PA", "Pará"),
    ("PB", "Paraíba"),
    ("PR", "Paraná"),
    ("PR", "Parma"),
    ("PV", "Pavia"),
    ("PA", "Pennsylvania"),
    ("PE", "Pernambuco"),
    ("PG", "Perugia"),
    ("PU", "Pesaro and Urbino"),
    ("PE", "Pescara"),
    ("PC", "Piacenza"),
    ("PI", "Piauí"),
    ("PI", "Pisa"),
    ("PT", "Pistoia"),
    ("PN", "Pordenone"),
    ("PZ", "Potenza"),
    ("PO", "Prato"),
    ("PE", "Prince Edward Island"),
    ("PY", "Puducherry"),
    ("PB", "Puebla"),
    ("PB", "Punjab"),
    ("63", "Qinghai"),
    ("QC", "Quebec"),
    ("QLD", "Queensland"),
    ("QE", "Querétaro"),
    ("QR", "Quintana Roo"),
    ("RG", "Ragusa"),
    ("RJ", "Rajasthan"),
    ("RA", "Ravenna"),
    ("RC", "Reggio Calabria"),
    ("RE", "Reggio Emilia"),
    ("RI", "Rhode Island"),
    ("RI", "Rieti"),
    ("RN", "Rimini"),
    ("RJ", "Rio de Janeiro"),
    ("RN", "Rio Grande do Norte"),
    ("RS", "Rio Grande do Sul"),
    ("RM", "Rome"),
    ("RO", "Rondônia"),
    ("RR", "Roraima"),
    ("RN", "Roscommon"),
    ("RO", "Rovigo"),
    ("SA", "Salerno"),
    ("SL", "San Luis Potosí"),
    ("SC", "Santa Catarina"),
    ("SP", "São Paulo"),
    ("SK", "Saskatchewan"),
    ("SS", "Sassari"),
    ("SV", "Savona"),
    ("SE", "Sergipe"),
    ("61", "Shaanxi"),
    ("37", "Shandong"),
    ("31", "Shanghai"),
    ("14", "Shanxi"),
    ("51", "Sichuan"),
    ("SI", "Siena"),
    ("SK", "Sikkim"),
    ("SI", "Sinaloa"),
    ("SO", "Sligo"),
    ("SO", "Sondrio"),
    ("SO", "Sonora"),
    ("SA", "South Australia"),
    ("SC", "South Carolina"),
    ("SD", "South Dakota"),
    ("SR", "Syracuse"),
    ("TB", "Tabasco"),
    ("TM", "Tamaulipas"),
    ("TN", "Tamil Nadu"),
    ("TA", "Taranto"),
    ("TAS", "Tasmania"),
    ("TN", "Tennessee"),
    ("TE", "Teramo"),
    ("TR", "Terni"),
    ("TX", "Texas"),
    ("12", "Tianjin"),
    ("TA", "Tipperary"),
    ("TL", "Tlaxcala"),
    ("TO", "Tocantins"),
    ("TP", "Trapani"),
    ("TN", "Trento"),
    ("TV", "Treviso"),
    ("TS", "Trieste"),
    ("TR", "Tripura"),
    ("TO", "Turin"),
    ("UD", "Udine"),
    ("UT", "Utah"),
    ("UT", "Uttarakhand"),
    ("UP", "Uttar Pradesh"),
    ("VA", "Varese"),
    ("VE", "Venice"),
    ("VE", "Veracruz"),
    ("VB", "Verbano-Cusio-Ossola"),
    ("VC", "Vercelli"),
    ("VT", "Vermont"),
    ("VR", "Verona"),
    ("VV", "Vibo Valentia"),
    ("VI", "Vicenza"),
    ("VIC", "Victoria"),
    ("VA", "Virginia"),
    ("VT", "Viterbo"),
    ("WA", "Washington"),
    ("WD", "Waterford"),
    ("WB", "West Bengal"),
    ("WA", "Western Australia"),
    ("WH", "Westmeath"),
    ("WV", "West Virginia"),
    ("WX", "Wexford"),
    ("WW", "Wicklow"),
    ("WI", "Wisconsin"),
    ("WY", "Wyoming"),
    ("65", "Xinjiang"),
    ("54", "Xizang"),
    ("YU", "Yucatán"),
    ("YT", "Yukon Territories"),
    ("53", "Yunnan"),
    ("ZA", "Zacatecas"),
    ("33", "Zhejiang"),
)

CURRENT_GRADE_CHOICES = (
    ("Graduating 8th", "Graduating 8th"),
    ("Freshman, 9th", "Freshman, 9th"),
    ("Sophomore, 10th", "Sophomore, 10th"),
    ("Junior, 11th", "Junior, 11th"),
    ("Senior, 12th", "Senior, 12th"),
)

STATUS_CHOICES = (
    ("Applied", "Applied"),
    ("Waitlisted", "Waitlisted"),
    ("Enrolled", "Enrolled"),
    ("Completed-Course", "Completed-Course"),
    ("Withdrew-Application", "Withdrew-Application"),
    ("Rejected", "Rejected"),
    ("Dropped", "Dropped"),
)

APP_WD_CHOICES = (
    ("Didn't show up for interview", "Didn't show up for interview"),
    ("Acceptance-offer-rejected", "Acceptance-offer-rejected"),
    ("Didn’t show up for class", "Didn’t show up for class"),
    ("Dropped in first 2 weeks", "Dropped in first 2 weeks"),
    ("Withdrew before interview", "Withdrew before interview"),
    ("Class Cancelled", "Class Cancelled"),
)

SEX_AT_BIRTH_CHOICES = (
    ("Female", "Female"),
    ("Male", "Male"),
    ("Decline to answer", "Decline to answer"),
)

SEXUAL_ORIENTATION_CHOICES = (
    ("Bisexual", "Bisexual"),
    ("Gay / Lesbian / Same-Gender Loving", "Gay / Lesbian / Same-Gender Loving"),
    ("Questioning / Unsure", "Questioning / Unsure"),
    ("Straight / Heterosexual", "Straight / Heterosexual"),
    ("Not Listed.", "Not Listed."),
    ("Decline to answer", "Decline to answer"),
)

HOUSEHOLD_TYPE_CHOICES = (
    ("Single Female Headed Family", "Single Female Headed Family"),
    ("Single Male Headed Family", "Single Male Headed Family"),
    ("Dual Headed Family", "Dual Headed Family"),
)

INCOME_CERT_CHOICES = (
    ("CalWorks", "CalWorks"),
    ("Food Stamps", "Food Stamps"),
    ("Medi-CAL", "Medi-CAL"),
    ("Tax Return (most recent)", "Tax Return (most recent)"),
    ("Unemployment (check stub)", "Unemployment (check stub)"),
    ("SSI**", "SSI**"),
    ("Payroll Stub**", "Payroll Stub**"),
    (
        "Other (i.e. public housing/foster care)**",
        "Other (i.e. public housing/foster care)**",
    ),
    ("Self-certified", "Self-certified"),
)

FAMILY_SIZE_CHOICES = (
    ("1 person", "1 person"),
    ("2 persons", "2 persons"),
    ("3 persons", "3 persons"),
    ("4 persons", "4 persons"),
    ("5 persons", "5 persons"),
    ("6 persons", "6 persons"),
    ("7 persons", "7 persons"),
    ("8 persons", "8 persons"),
    ("9+ persons", "9+ persons"),
)

INCOME_LEVEL_CHOICES = (
    (
        "Extremely Low Income $0 - 27,650 (1 person)",
        "Extremely Low Income $0 - 27,650 (1 person)",
    ),
    (
        "Low Income $27,651 - 46,100 (1 person)",
        "Low Income $27,651 - 46,100 (1 person)",
    ),
    (
        "Moderate Income $46,101 - 73,750 (1 person)",
        "Moderate Income $46,101 - 73,750 (1 person)",
    ),
    (
        "Above Moderate Income $73,751 or greater (1 person)",
        "Above Moderate Income $73,751 or greater (1 person)",
    ),
    (
        "Extremely Low Income $0 - 31,600 (2 persons)",
        "Extremely Low Income $0 - 31,600 (2 persons)",
    ),
    (
        "Low Income $31,601 - 52,650 (2 persons)",
        "Low Income $31,601 - 52,650 (2 persons)",
    ),
    (
        "Moderate Income $52,651 - 84,300 (2 persons)",
        "Moderate Income $52,651 - 84,300 (2 persons)",
    ),
    (
        "Above Moderate Income $84,301 or greater (2 persons)",
        "Above Moderate Income $84,301 or greater (2 persons)",
    ),
    (
        "Extremely Low Income $0 - 35,550 (3 persons)",
        "Extremely Low Income $0 - 35,550 (3 persons)",
    ),
    (
        "Low Income $35,551 - 59,250 (3 persons)",
        "Low Income $35,551 - 59,250 (3 persons)",
    ),
    (
        "Moderate Income $59,251 - 94,850 (3 persons)",
        "Moderate Income $59,251 - 94,850 (3 persons)",
    ),
    (
        "Above Moderate Income $94,851 or greater (3 persons)",
        "Above Moderate Income $94,851 or greater (3 persons)",
    ),
    (
        "Extremely Low Income $0 - 39,500 (4 persons)",
        "Extremely Low Income $0 - 39,500 (4 persons)",
    ),
    (
        "Low Income $39,501 - 65,800 (4 persons)",
        "Low Income $39,501 - 65,800 (4 persons)",
    ),
    (
        "Moderate Income $65,801 - 105,350 (4 persons)",
        "Moderate Income $65,801 - 105,350 (4 persons)",
    ),
    (
        "Above Moderate Income $105,351 or greater (4 persons)",
        "Above Moderate Income $105,351 or greater (4 persons)",
    ),
    (
        "Extremely Low Income $0 - 42,700 (5 persons)",
        "Extremely Low Income $0 - 42,700 (5 persons)",
    ),
    (
        "Low Income $42,701 - 71,100 (5 persons)",
        "Low Income $42,701 - 71,100 (5 persons)",
    ),
    (
        "Moderate Income $71,101 - 113,800 (5 persons)",
        "Moderate Income $71,101 - 113,800 (5 persons)",
    ),
    (
        "Above Moderate Income $113,801 or greater (5 persons)",
        "Above Moderate Income $113,801 or greater (5 persons)",
    ),
    (
        "Extremely Low Income $0 - 45,850 (6 persons)",
        "Extremely Low Income $0 - 45,850 (6 persons)",
    ),
    (
        "Low Income $45,851 - 76,350 (6 persons)",
        "Low Income $45,851 - 76,350 (6 persons)",
    ),
    (
        "Moderate Income $76,351 - 122,250 (6 persons)",
        "Moderate Income $76,351 - 122,250 (6 persons)",
    ),
    (
        "Above Moderate Income $122,251 or greater (6 persons)",
        "Above Moderate Income $122,251 or greater (6 persons)",
    ),
    (
        "Extremely Low Income $0 - 49,000 (7 persons)",
        "Extremely Low Income $0 - 49,000 (7 persons)",
    ),
    (
        "Low Income $49,001 - 81,600 (7 persons)",
        "Low Income $49,001 - 81,600 (7 persons)",
    ),
    (
        "Moderate Income $81,601 - 130,650 (7 persons)",
        "Moderate Income $81,601 - 130,650 (7 persons)",
    ),
    (
        "Above Moderate Income $130,651 or greater (7 persons)",
        "Above Moderate Income $130,651 or greater (7 persons)",
    ),
    (
        "Extremely Low Income $0 - 52,150 (8 persons)",
        "Extremely Low Income $0 - 52,150 (8 persons)",
    ),
    (
        "Low Income $52,151 - 86,900 (8 persons)",
        "Low Income $52,151 - 86,900 (8 persons)",
    ),
    (
        "Moderate Income $86,901 - 139,100 (8 persons)",
        "Moderate Income $86,901 - 139,100 (8 persons)",
    ),
    (
        "Above Moderate Income $139,101 or greater (8 persons)",
        "Above Moderate Income $139,101 or greater (8 persons)",
    ),
)
