# Generated by Django 2.2.1 on 2019-06-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("staff", "0003_contact")]

    operations = [migrations.DeleteModel(name="Contact")]
