# Generated by Django 2.2 on 2019-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0002_users_email")]

    operations = [
        migrations.AlterField(
            model_name="users", name="role", field=models.CharField(max_length=15)
        )
    ]
