# Generated by Django 2.2.3 on 2019-07-22 22:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("home", "0002_auto_20190714_0448")]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="attendance_summary",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=None, null=True
            ),
        )
    ]
