# Generated by Django 2.2 on 2019-05-28 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("home", "0003_auto_20190527_1523")]

    operations = [migrations.RemoveField(model_name="users", name="username")]
