# Generated by Django 2.2.3 on 2019-08-02 01:26

from django.db import migrations, models
import django.db.models.deletion
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [("home", "0003_announcementdistribution")]

    operations = [
        migrations.AddField(
            model_name="session",
            name="classroom",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_session",
                to="home.Classroom",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="date",
            field=models.DateField(default="1901-01-01"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="race",
            field=salesforce.fields.CharField(
                blank=True,
                choices=[
                    (
                        "American Indian/Alaskan Native",
                        "American Indian/Alaskan Native",
                    ),
                    ("Asian", "Asian"),
                    ("Black/African American", "Black/African American"),
                    (
                        "Native Hawaiian/Other Pacific Islander",
                        "Native Hawaiian/Other Pacific Islander",
                    ),
                    ("White", "White"),
                    (
                        "American Indian/Alaskan Native AND Black/African American",
                        "American Indian/Alaskan Native AND Black/African American",
                    ),
                    (
                        "American Indian/Alaskan Native AND White",
                        "American Indian/Alaskan Native AND White",
                    ),
                    ("Asian AND White", "Asian AND White"),
                    (
                        "Black/African American AND White",
                        "Black/African American AND White",
                    ),
                    ("Other/Multiracial", "Other/Multiracial"),
                ],
                max_length=255,
                null=True,
                verbose_name="Which best describes your race?",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="which_best_describes_your_ethnicity",
            field=salesforce.fields.CharField(
                blank=True,
                choices=[
                    ("Hispanic/Latinx", "Hispanic/Latinx"),
                    ("Not Hispanic/Latinx", "Not Hispanic/Latinx"),
                ],
                db_column="Which_best_describes_your_ethnicity__c",
                max_length=255,
                null=True,
                verbose_name="Which best describes your ethnicity?",
            ),
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(default="No Title", max_length=240)),
                ("description", models.TextField(max_length=2000)),
                ("link", models.URLField(default=None, null=True)),
                ("file", models.FileField(default=None, null=True, upload_to="")),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_resource",
                        to="home.Classroom",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_resource",
                        to="home.Session",
                    ),
                ),
            ],
        ),
    ]
