# Generated by Django 2.2.3 on 2019-08-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0004_auto_20190802_0126")]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="in_classroom",
            field=models.BooleanField(default=False),
        )
    ]
