# Generated by Django 2.2.3 on 2019-07-28 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, unique=True)),
                ('template', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(default='No Description Available', max_length=2500),
        ),
        migrations.CreateModel(
            name='FormDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_to_be_signed', to='home.Form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_signer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='esign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esign_form', to='home.Esign'),
        ),
    ]
