# Generated by Django 2.2.3 on 2019-08-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0005_userprofile_in_classroom")]

    operations = [
        migrations.AddField(
            model_name="session",
            name="title",
            field=models.CharField(default="No Title", max_length=240),
        )
    ]
