# Generated by Django 2.2.3 on 2019-07-29 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_auto_20190728_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='esign',
            name='created_by',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='esign_creator_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
