# Generated by Django 2.2.3 on 2019-08-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190803_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='in_classroom',
        ),
    ]
