# Generated by Django 2.2.3 on 2019-07-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_esign_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(max_length=2500),
        ),
    ]
