# Generated by Django 2.2 on 2019-06-18 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190528_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
