# Generated by Django 2.2.3 on 2019-08-06 19:17

from django.db import migrations, models
import home.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190804_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form',
            field=models.FileField(upload_to=home.models.models.upload_to),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=home.models.models.upload_to),
        ),
        migrations.AlterField(
            model_name='session',
            name='activity',
            field=models.FileField(default=None, upload_to=home.models.models.upload_to),
        ),
        migrations.AlterField(
            model_name='session',
            name='lecture',
            field=models.FileField(default=None, upload_to=home.models.models.upload_to),
        ),
        migrations.AlterField(
            model_name='session',
            name='lesson_plan',
            field=models.FileField(default=None, upload_to=home.models.models.upload_to),
        ),
    ]
