# Generated by Django 2.2.4 on 2019-09-02 01:27

from django.db import migrations, models
import django.db.models.deletion
import salesforce.backend.operations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190806_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='meeting_days',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='ClassMeeting',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', salesforce.fields.BooleanField(default=False, verbose_name='Deleted')),
                ('name', salesforce.fields.CharField(blank=True, default=salesforce.backend.operations.DefaultedOnCreate(), max_length=80, null=True, verbose_name='Class Meeting Name')),
                ('created_date', salesforce.fields.DateTimeField()),
                ('last_modified_date', salesforce.fields.DateTimeField()),
                ('system_modstamp', salesforce.fields.DateTimeField()),
                ('date', salesforce.fields.DateField(blank=True, null=True)),
                ('start_time', salesforce.fields.TimeField(blank=True, db_column='Start_Time__c', null=True, verbose_name='Start Time')),
                ('end_time', salesforce.fields.TimeField(blank=True, db_column='End_Time__c', null=True, verbose_name='End Time')),
                ('duration_hours', salesforce.fields.DecimalField(blank=True, db_column='Duration_hours__c', decimal_places=0, max_digits=2, null=True, verbose_name='Duration (hours)')),
                ('class_offering', salesforce.fields.ForeignKey(db_column='Class_Offering__c', on_delete=django.db.models.deletion.DO_NOTHING, to='home.ClassOffering')),
                ('created_by', salesforce.fields.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classmeeting_createdby_set', to='home.User')),
                ('last_modified_by', salesforce.fields.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classmeeting_lastmodifiedby_set', to='home.User')),
            ],
            options={
                'verbose_name': 'Class Meeting',
                'verbose_name_plural': 'Class Meetings',
                'db_table': 'Class_Meeting__c',
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', salesforce.fields.BooleanField(default=False, verbose_name='Deleted')),
                ('name', salesforce.fields.CharField(max_length=80, verbose_name='Class Attendance #')),
                ('created_date', salesforce.fields.DateTimeField()),
                ('last_modified_date', salesforce.fields.DateTimeField()),
                ('system_modstamp', salesforce.fields.DateTimeField()),
                ('status', salesforce.fields.CharField(blank=True, choices=[('Present', 'Present'), ('Late', 'Late'), ('Excused', 'Excused'), ('Absent', 'Absent'), ('Signed-up', 'Signed-up')], max_length=255, null=True)),
                ('class_meeting_date', salesforce.fields.DateField(blank=True, db_column='Class_Meeting_Date__c', null=True, verbose_name='Class Meeting Date')),
                ('assessment_score', salesforce.fields.DecimalField(blank=True, db_column='Assessment_Score__c', decimal_places=0, max_digits=1, null=True, verbose_name='Assessment Score')),
                ('teacher_s_notes', salesforce.fields.TextField(blank=True, db_column='Teacher_s_Notes__c', null=True, verbose_name="Teacher's Notes")),
                ('class_meeting', salesforce.fields.ForeignKey(db_column='Class_Meeting__c', on_delete=django.db.models.deletion.DO_NOTHING, to='home.ClassMeeting')),
                ('contact', salesforce.fields.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Contact')),
                ('created_by', salesforce.fields.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classattendance_createdby_set', to='home.User')),
                ('last_modified_by', salesforce.fields.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classattendance_lastmodifiedby_set', to='home.User')),
            ],
            options={
                'verbose_name': 'Class Attendance',
                'verbose_name_plural': 'Class Attendance',
                'db_table': 'Class_Attendance__c',
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
