# Generated by Django 2.2.1 on 2019-06-21 22:59

from django.db import migrations
import salesforce.backend.operations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190621_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=salesforce.fields.BooleanField(default=salesforce.backend.operations.DefaultedOnCreate(), verbose_name='Active'),
        ),
    ]
