# Generated by Django 2.2.1 on 2019-06-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0015_classroom")]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(default="1901-01-01"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="salesforce_id",
            field=models.CharField(default="xxxxxx01011901", max_length=14),
        ),
    ]
