# Generated by Django 2.2.1 on 2019-06-24 05:21

from django.db import migrations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [("home", "0016_auto_20190624_0318")]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="client_id",
            field=salesforce.fields.CharField(
                blank=True,
                db_column="Client_ID__c",
                help_text='3 first letters of first name, 3 first letters of last name, and birthdate "AAABBB00000000" (Only used for students and parents). This field is auto-populated by FormAssembly.',
                max_length=14,
                null=True,
                verbose_name="Client ID",
            ),
        )
    ]
