# Generated by Django 2.2.1 on 2019-06-25 03:21

from django.db import migrations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [("home", "0018_contact_npsp_primary_affiliation")]

    operations = [
        migrations.AlterField(
            model_name="classoffering",
            name="course_short_name",
            field=salesforce.fields.CharField(
                blank=True,
                db_column="Course_short_name__c",
                max_length=80,
                null=True,
                verbose_name="Course short name",
            ),
        )
    ]
