# Generated by Django 2.2.1 on 2019-06-25 04:15

from django.db import migrations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190625_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classoffering',
            name='name',
            field=salesforce.fields.CharField(default='ClassName', max_length=80, verbose_name='Class Offering Name'),
        ),
    ]
