# Generated by Django 2.2.1 on 2019-06-25 04:36

from django.db import migrations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20190625_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classoffering',
            name='name',
            field=salesforce.fields.CharField(blank=True, default='Nada', max_length=80, null=True, verbose_name='Class Offering Name'),
        ),
    ]
