# Generated by Django 2.2.1 on 2019-06-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("home", "0024_auto_20190625_0437")]

    operations = [
        migrations.RemoveField(model_name="classoffering", name="course_short_name")
    ]
