# Generated by Django 2.2.1 on 2019-06-25 05:19

from django.db import migrations
import salesforce.backend.operations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [("home", "0025_remove_classoffering_course_short_name")]

    operations = [
        migrations.AlterField(
            model_name="classoffering",
            name="name",
            field=salesforce.fields.CharField(
                blank=True,
                default=salesforce.backend.operations.DefaultedOnCreate(),
                max_length=80,
                null=True,
                verbose_name="Class Offering Name",
            ),
        )
    ]
