# Generated by Django 2.2.3 on 2019-07-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0027_auto_20190630_2257")]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="salesforce_id",
            field=models.CharField(default="xxxxxx19010101", max_length=14),
        )
    ]
