# Generated by Django 2.2.1 on 2019-06-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('home', '0027_auto_20190630_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='recipient_groups',
            field=models.ManyToManyField(related_name='user_groups', to='auth.Group'),
        ),
    ]
