# Generated by Django 2.2.1 on 2019-06-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_announcement_recipient_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='recipient_classrooms',
            field=models.ManyToManyField(related_name='classroom', to='home.Classroom'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcement',
            field=models.TextField(max_length=2500),
        ),
    ]
