# Generated by Django 2.2.3 on 2019-07-11 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("home", "0029_auto_20190711_0406")]

    operations = [
        migrations.RemoveField(model_name="session", name="templates"),
        migrations.AddField(
            model_name="templates",
            name="session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session",
                to="home.Session",
            ),
        ),
    ]
