# Generated by Django 2.2.3 on 2019-07-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20190711_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='notes',
            field=models.TextField(default='', max_length=500),
        ),
    ]
