# Generated by Django 2.2.3 on 2019-07-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20190711_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='sessions',
        ),
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='1901-01-01'),
        ),
        migrations.AddField(
            model_name='session',
            name='activity',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(default='No Description Available', max_length=2000),
        ),
        migrations.AddField(
            model_name='session',
            name='lesson_plan',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='session',
            name='video',
            field=models.URLField(default=None),
        ),
    ]
